apiVersion: v1
kind: Service
metadata:
  name: sample-app-svc
spec:
  type: NodePort
  selector:
    app: sample-app
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30081
